data:
  dataset: "ImageNet"
  category: ""
  image_size: 64
  channels: 3
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: false
  rescaled: false
  num_workers: 16
  out_of_dist: false
  subset_1k: false